#!/usr/bin/env bats
# tests/security/heredoc-injection.bats
# Test that heredoc patterns don't execute injected shell commands

setup() {
  # Clean up any canary files from previous runs (unique per test for parallel execution)
  export CANARY_PREFIX="/tmp/sharkrite-heredoc-canary-$$-${BATS_TEST_NUMBER}"
  rm -f "${CANARY_PREFIX}"*

  # Source necessary libraries
  export RITE_PROJECT_ROOT="/tmp/test-project-$$"
  export RITE_DATA_DIR=".rite"
  mkdir -p "$RITE_PROJECT_ROOT/$RITE_DATA_DIR"

  # Create minimal test environment
  export RITE_LIB_DIR="$(cd "$(dirname "$BATS_TEST_DIRNAME")/../lib" && pwd)"
}

teardown() {
  # Clean up canary files
  rm -f "${CANARY_PREFIX}"*
  rm -rf "/tmp/test-project-$$"
}

# Test 1: create-followup-issues.sh - PR title injection
@test "create-followup-issues.sh: malicious PR title does not execute" {
  # Skip if file doesn't have the function (dependency issue)
  [ -f "$RITE_LIB_DIR/utils/create-followup-issues.sh" ] || skip "create-followup-issues.sh not found"

  source "$RITE_LIB_DIR/utils/colors.sh"
  source "$RITE_LIB_DIR/utils/create-followup-issues.sh"

  # Inject payload into PR title
  export PR_NUMBER="123"
  export PR_TITLE="Fix bug \$(touch ${CANARY_PREFIX}-pr)"
  export PRIORITY="HIGH"
  export LOCATION="test.sh:10"
  export PROBLEM="Test problem"
  export WHY="Test reason"
  export RECOMMENDATION="Test fix"

  # The vulnerable pattern was: ISSUE_BODY=$(cat <<EOF ... $PR_TITLE ... EOF)
  # After fix, it should be: ISSUE_BODY="... $PR_TITLE ..."
  # Neither should execute the command, but heredoc was vulnerable to recursive expansion

  # We can't easily call the full function without GH CLI, so test the pattern directly
  local ISSUE_BODY="## From PR Review
PR #${PR_NUMBER} - ${PR_TITLE}

## Priority
${PRIORITY}"

  # Verify canary was not created
  [ ! -f ${CANARY_PREFIX}-pr ]
}

# Test 2: scratchpad-manager.sh - description/fix injection
@test "scratchpad-manager.sh: malicious description does not execute" {
  [ -f "$RITE_LIB_DIR/utils/scratchpad-manager.sh" ] || skip "scratchpad-manager.sh not found"

  # Test the pattern directly
  local description="Test \$(touch ${CANARY_PREFIX}-description)"
  local location="test.sh:20"
  local affects="tests"
  local fix="Apply \$(touch ${CANARY_PREFIX}-fix) patch"
  local done_criteria="Tests pass"
  local origin_text="Manual test"

  # The fixed pattern (plain string, not heredoc)
  local issue_body="## Description
${description}

## Location
\`${location}\`

## Impact
Affects: ${affects}

## Intended Fix
${fix}

## Done Criteria
- [ ] ${done_criteria}
- [ ] Tests pass
- [ ] No regressions introduced

## Origin
${origin_text}

---
_Auto-generated by sharkrite workflow from encountered issues log_"

  # Verify canaries were not created
  [ ! -f ${CANARY_PREFIX}-description ]
  [ ! -f ${CANARY_PREFIX}-fix ]
}

# Test 3: create-pr.sh - issue title/changes summary injection
@test "create-pr.sh: malicious issue title does not execute" {
  [ -f "$RITE_LIB_DIR/core/create-pr.sh" ] || skip "create-pr.sh not found"

  # Test the pattern
  local ISSUE_NUMBER="42"
  local ISSUE_TITLE="Add feature \$(touch ${CANARY_PREFIX}-issue)"
  local CHANGES_SUMMARY="Modified \$(touch ${CANARY_PREFIX}-summary) files"
  local CURRENT_BRANCH="feat/test"
  local BASE_BRANCH="main"

  # The fixed pattern (plain string)
  local PR_BODY="## Summary

$(if [ ! -z "$ISSUE_NUMBER" ]; then echo "Closes #${ISSUE_NUMBER}"; fi)

${ISSUE_TITLE}

${CHANGES_SUMMARY}

## Testing

- [x] Code builds successfully"

  # Verify canaries were not created
  [ ! -f ${CANARY_PREFIX}-issue ]
  [ ! -f ${CANARY_PREFIX}-summary ]
}

# Test 4: Comprehensive grep check - no unquoted heredoc-in-$() patterns remain
@test "no unquoted heredoc-in-\$() patterns in lib/" {
  cd "$(dirname "$RITE_LIB_DIR")"

  # This pattern matches: $(cat <<EOF  or  $(cat <<eof  or  $(cat <<-EOF
  # But excludes: $(cat <<'EOF'  (quoted delimiter - safe)
  # Also excludes: cat > file <<EOF  (write-to-file, not capture - safe)
  #
  # Pattern breakdown:
  # - \$\(cat <<-?     : matches $(cat << or $(cat <<-
  # - [a-zA-Z_][a-zA-Z0-9_]*  : matches any valid shell word (delimiter)
  # - Not followed by single quote (the grep -v below handles quoted delimiters)

  # Find all unquoted heredoc-in-command-substitution patterns
  local matches=$(grep -rnE '\$\(cat <<-?[a-zA-Z_][a-zA-Z0-9_]*' lib/ | grep -v "cat > " | grep -v "<<'" || true)

  # Debugging: show what we found
  if [ -n "$matches" ]; then
    echo "Found unquoted heredoc patterns:" >&2
    echo "$matches" >&2
  fi

  # Should have zero matches
  [ -z "$matches" ]
}
