#!/bin/bash
# lib/utils/encountered-issues-renderer.sh
#
# Renders docs/architecture/encountered-issues.md from closed GitHub issues
# tagged with the `recurring-pattern` label.
#
# Each labeled issue represents one bug class that recurred 2+ times during
# dogfooding. The rendered file lists each pattern, its instances, root cause,
# and mitigation — so future Claude sessions can diagnose similar bugs faster.
#
# Usage (standalone): lib/utils/encountered-issues-renderer.sh
# Usage (via rite):   rite --refresh-encountered-issues
# Usage (in tests):   RITE_SOURCE_FUNCTIONS_ONLY=1 source encountered-issues-renderer.sh

set -euo pipefail

# Re-source guard: skip if already loaded (idempotent sourcing)
if declare -f render_encountered_issues >/dev/null 2>&1; then
  return 0 2>/dev/null || true
fi

# Source config if not already loaded
if [ -z "${RITE_LIB_DIR:-}" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "$SCRIPT_DIR/config.sh"
fi

source "$RITE_LIB_DIR/utils/colors.sh"
source "$RITE_LIB_DIR/utils/gh-retry.sh"

# ---------------------------------------------------------------------------
# render_encountered_issues()
#
# Fetches closed issues with `recurring-pattern` label from GitHub, renders
# sorted markdown to OUTPUT_FILE (defaults to docs/architecture/encountered-issues.md).
#
# Environment:
#   RITE_PROJECT_ROOT  — project root (set by config.sh)
#   OUTPUT_FILE        — override output path (optional, for testing)
#
# Exit codes:
#   0 — rendered successfully
#   1 — gh CLI unavailable or fetch failed
# ---------------------------------------------------------------------------
render_encountered_issues() {
  local output_file="${OUTPUT_FILE:-$RITE_PROJECT_ROOT/docs/architecture/encountered-issues.md}"
  local label="recurring-pattern"

  # Ensure output directory exists
  mkdir -p "$(dirname "$output_file")"

  print_info "Fetching closed issues with label '$label'..." >&2

  # Fetch issues. Sort is applied in jq: ascending by number (stable).
  # gh_safe provides retry + resilience (from lib/utils/gh-retry.sh).
  local issues_json
  issues_json=$(gh_safe issue list \
    --label "$label" \
    --state closed \
    --json number,title,body,closedAt,closedByPullRequestsReferences \
    --limit 200 2>/dev/null || true)
  issues_json="${issues_json:-[]}"

  local count
  count=$(echo "$issues_json" | jq 'length' 2>/dev/null || echo "0")

  print_info "Found $count issue(s) with label '$label'" >&2

  # Sort by issue number ascending (stable, deterministic output)
  local sorted_json
  sorted_json=$(echo "$issues_json" | jq 'sort_by(.number)' 2>/dev/null || echo "[]")

  local today
  today=$(date '+%Y-%m-%d')

  # ── Write header ──────────────────────────────────────────────────────────
  {
    echo "<!-- Auto-generated by encountered-issues-renderer.sh. Do not hand-edit."
    echo "     To add a pattern: label the originating issue \`recurring-pattern\`"
    echo "     and run \`rite --refresh-encountered-issues\`."
    echo "     Last refreshed: $today -->"
    echo ""
    echo "# Encountered Issues — Recurring Bug Pattern Catalog"
    echo ""
    echo "> **Auto-generated. Do not hand-edit.** To add a pattern, label the"
    echo "> originating issue \`recurring-pattern\` and run \`rite --refresh-encountered-issues\`."
    echo ""
    echo "This catalog lists bug classes that recurred 2+ times during Sharkrite"
    echo "dogfooding. Its purpose: let future Claude sessions recognize a familiar"
    echo "pattern quickly and apply the known fix rather than re-diagnosing from scratch."
    echo ""
    echo "Each entry includes: the pattern name, recurrence instances (PRs + dates),"
    echo "root-cause class, and the mitigation or lint rule that prevents recurrence."
    echo ""
    if [ "$count" -eq 0 ]; then
      echo "---"
      echo ""
      echo "_No recurring patterns recorded yet. Label closed issues with_"
      echo "_\`recurring-pattern\` and re-run \`rite --refresh-encountered-issues\`._"
    else
      echo "## Table of Contents"
      echo ""

      # TOC: one entry per issue
      local i=0
      while [ "$i" -lt "$count" ]; do
        local title number anchor
        title=$(echo "$sorted_json" | jq -r ".[$i].title" 2>/dev/null || echo "")
        number=$(echo "$sorted_json" | jq -r ".[$i].number" 2>/dev/null || echo "")
        # GitHub-style anchor: lowercase, spaces→hyphens, strip non-alphanum-hyphen
        anchor=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g' | sed 's/--*/-/g' || true)
        echo "- [#${number}: ${title}](#${anchor})"
        i=$((i + 1))
      done

      echo ""
      echo "---"

      # ── One entry per issue ──────────────────────────────────────────────
      i=0
      while [ "$i" -lt "$count" ]; do
        local issue_number issue_title issue_body issue_closed_at pr_refs_json
        issue_number=$(echo "$sorted_json" | jq -r ".[$i].number" 2>/dev/null || echo "")
        issue_title=$(echo "$sorted_json" | jq -r ".[$i].title" 2>/dev/null || echo "")
        issue_body=$(echo "$sorted_json" | jq -r ".[$i].body // \"\"" 2>/dev/null || echo "")
        issue_closed_at=$(echo "$sorted_json" | jq -r ".[$i].closedAt // \"\"" 2>/dev/null | cut -dT -f1 || echo "")
        pr_refs_json=$(echo "$sorted_json" | jq -r ".[$i].closedByPullRequestsReferences" 2>/dev/null || echo "[]")

        echo ""
        echo "## ${issue_title}"
        echo ""

        # ── Instances ───────────────────────────────────────────────────────
        echo "**Issue:** [#${issue_number}](https://github.com/lifeunsubscribe/Sharkrite/issues/${issue_number})"
        echo ""

        # Closing PRs (sorted by number)
        local pr_count
        pr_count=$(echo "$pr_refs_json" | jq 'length' 2>/dev/null || echo "0")
        if [ "$pr_count" -gt 0 ]; then
          echo "**Fixed by:**"
          echo ""
          local pr_sorted
          pr_sorted=$(echo "$pr_refs_json" | jq 'sort_by(.number)' 2>/dev/null || echo "[]")
          local j=0
          while [ "$j" -lt "$pr_count" ]; do
            local pr_num
            pr_num=$(echo "$pr_sorted" | jq -r ".[$j].number" 2>/dev/null || echo "")
            echo "- PR [#${pr_num}](https://github.com/lifeunsubscribe/Sharkrite/pull/${pr_num})"
            j=$((j + 1))
          done
          echo ""
        fi

        [ -n "$issue_closed_at" ] && echo "**Closed:** ${issue_closed_at}" && echo ""

        # ── Body sections ────────────────────────────────────────────────────
        # Extract the **Description**: field from the standard Sharkrite issue
        # template, or fall back to structured ## sections, or a raw excerpt.
        _render_body_sections "$issue_body"

        echo "---"

        i=$((i + 1))
      done
    fi
  } > "$output_file"

  print_success "Wrote $count pattern(s) to $output_file" >&2
  echo "$output_file"
}

# ---------------------------------------------------------------------------
# _render_body_sections(body)
#
# Extracts meaningful content from an issue body in priority order:
#
#   1. **Description**: field (standard Sharkrite issue template — after the
#      "---" divider that follows the Bug Confirmation block)
#   2. Canonical ## headings: Description, Root Cause, Variants, Mitigation,
#      Related (for custom recurring-pattern issues with explicit structure)
#   3. First meaningful prose paragraph after any ## block (fallback)
#
# Intentionally skips: Bug confirmation blocks, code blocks, bash commands.
# ---------------------------------------------------------------------------
_render_body_sections() {
  local body="$1"

  if [ -z "$body" ]; then
    echo "_No description._"
    echo ""
    return
  fi

  # ── Strategy 1: Extract **Description**: from standard Sharkrite template ──
  # The template puts "---\n\n**Time**: ...\n\n**Description**:\nProse here\n\n"
  # after the Bug Confirmation block. Extract the Description value.
  local description_text
  # Extract the **Description**: block: from the header line through the next
  # **Bold**: header / ## heading / --- divider. The awk script is kept on a
  # single line so sharkrite-lint Rule 8's next-line lookahead picks up `|| true`.
  description_text=$(echo "$body" | awk '/^\*\*Description\*\*:/ { found = 1; remainder = $0; sub(/^\*\*Description\*\*:[[:space:]]*/, "", remainder); if (remainder != "") buf = remainder; next } found == 1 { if (/^\*\*[A-Za-z].*\*\*:/ || /^## / || /^---$/) { found = 2; exit } buf = (buf == "" ? $0 : buf "\n" $0) } END { if (buf != "") print buf }' || true)
  description_text="${description_text:-}"

  if [ -n "$description_text" ]; then
    # Strip leading/trailing blank lines (portable awk — no BSD-sed \n quirks).
    # Inlined onto one line so Rule 8's next-line lookahead picks up `|| true`.
    description_text=$(echo "$description_text" | awk '/[^[:space:]]/ { found=1 } found { lines[n++] = $0 } END { while (n > 0 && lines[n-1] ~ /^[[:space:]]*$/) n--; for (i = 0; i < n; i++) print lines[i] }' || true)
    if [ -n "$description_text" ]; then
      echo "**Description:**"
      echo ""
      echo "$description_text"
      echo ""
      return
    fi
  fi

  # ── Strategy 2: Canonical ## headings ────────────────────────────────────
  # Used when the issue was written with explicit structure (## Root Cause etc.)
  if echo "$body" | grep -qE '^## (Description|Root Cause|Variants|Mitigation|Related)$'; then
    echo "$body" | awk '
      /^## (Description|Root Cause|Variants|Mitigation|Related)$/ {
        if (buf != "" && current != "") {
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf)
          print "**" current ":**"
          print ""
          print buf
          print ""
        }
        current = $0
        sub(/^## /, "", current)
        buf = ""
        next
      }
      /^## / { current = ""; buf = ""; next }
      current != "" { buf = (buf == "" ? $0 : buf "\n" $0) }
      END {
        if (buf != "" && current != "") {
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf)
          print "**" current ":**"
          print ""
          print buf
          print ""
        }
      }
    '
    return
  fi

  # ── Strategy 3: First prose paragraph after the "---" divider ────────────
  # Skip the Bug Confirmation block entirely (before the first "---"), then
  # extract the first non-empty, non-code prose paragraph.
  local prose_excerpt
  # First prose paragraph after the "---" divider, skipping headings, code
  # blocks, and standard Sharkrite sections. Inlined onto one line so Rule 8's
  # next-line lookahead picks up `|| true`.
  prose_excerpt=$(echo "$body" | awk '/^---$/ { past_divider = 1; next } past_divider != 1 { next } /^## / { next } /^```/ { in_code = !in_code; next } in_code { next } /^\*\*Time\*\*:/ { next } /^\*\*Claude Context\*\*:/ { exit } /^\*\*Acceptance Criteria\*\*:/ { exit } /^[[:space:]]*$/ { if (chars > 0) { blanks++; if (blanks >= 2) exit } next } { blanks = 0; print; chars += length($0); if (chars > 600) exit }' | head -20 || true)

  if [ -n "$prose_excerpt" ]; then
    echo "**Summary:**"
    echo ""
    echo "$prose_excerpt"
    echo ""
  else
    echo "_See [issue body](https://github.com/lifeunsubscribe/Sharkrite/issues/) for details._"
    echo ""
  fi
}

# ---------------------------------------------------------------------------
# Function-only guard: when sourced with RITE_SOURCE_FUNCTIONS_ONLY=1, stop
# here so tests can load only function definitions without running the program.
# ---------------------------------------------------------------------------
if [ "${RITE_SOURCE_FUNCTIONS_ONLY:-}" = "1" ]; then
  return 0 2>/dev/null || true
fi

# ── Executable body (runs when invoked directly) ──────────────────────────

if [ -z "${RITE_PROJECT_ROOT:-}" ]; then
  echo "ERROR: RITE_PROJECT_ROOT is not set. Source config.sh first or run via 'rite --refresh-encountered-issues'." >&2
  exit 1
fi

render_encountered_issues
